
export const ActionTypes =
{
    ADDCAT: "ADDCATEGORY",
    ADDPRO: "ADDPRODUCT",
    VIEWPRO: "VIEWPRODUCT",
    VIEWCAT: "VIEWCATEGORY",
    UPDATECAT: "UPDATECATEGORY",
    UPDATEPRO: "UPDATEPRODUCT",
    REMOVECAT: "REMOVECATEGORY",
    REMOVEPRO: "REMOVEPRODUCT",
};